name: Codex Runtime
on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  run-codex:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - run: ./run_and_log.sh stacks/kim_watson_stack.yaml
      - run: cd PreservationVault && git push
