#!/usr/bin/env node
// managed-by: activ8-ai-context-pack | pack-version: 1.2.0
// source-sha: a0d4785

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { runSourceQueryLadder } from "./query-source-ladder.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(__dirname, "..");
const argv = process.argv.slice(2);

function argValue(name) {
  const idx = argv.indexOf(name);
  if (idx === -1) return null;
  return argv[idx + 1] ?? null;
}

const outPath = argValue("--out") || path.join(REPO_ROOT, "memory", "session-brief.md");
const sourceBootstrapQueries = (
  process.env.SESSION_BOOTSTRAP_SOURCE_QUERIES
    || "Traceability Hub,Intelligence Sweep Index,Prompt Library"
)
  .split(",")
  .map((item) => item.trim())
  .filter(Boolean)
  .slice(0, 3);

async function readText(filePath) {
  try {
    return await fs.readFile(filePath, "utf8");
  } catch {
    return null;
  }
}

function firstNonEmptyLine(text) {
  if (!text) return "not found";
  const line = text.split(/\r?\n/).map((item) => item.trim()).find(Boolean);
  return line || "not found";
}

function formatCTTimestamp(date) {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone: "America/Chicago",
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
  })
    .formatToParts(date)
    .reduce((acc, part) => {
      if (part.type !== "literal") acc[part.type] = part.value;
      return acc;
    }, {});
  return `${parts.year}-${parts.month}-${parts.day} ${parts.hour}:${parts.minute} CT`;
}

const memoryIndexPath = path.join(REPO_ROOT, "memory", "MEMORY.md");
const keyLessonsPath = path.join(REPO_ROOT, "memory", "key-lessons.md");
const operatorPrefsPath = path.join(REPO_ROOT, "memory", "operator-preferences-learn-me.md");

const [memoryIndex, keyLessons, operatorPrefs] = await Promise.all([
  readText(memoryIndexPath),
  readText(keyLessonsPath),
  readText(operatorPrefsPath),
]);

const sourceBootstrapResults = await Promise.all(
  sourceBootstrapQueries.map(async (query) => {
    try {
      const result = await runSourceQueryLadder({ query, limit: 2 });
      return {
        query,
        cacheHit: result.meta?.cache_hit === true,
        hits:
          (result.repo_anchors?.length || 0)
          + (result.repo_mirrors?.length || 0)
          + (result.downloads_evidence?.length || 0),
        nextStep: result.live_notion_confirmation,
      };
    } catch (error) {
      const errorMessage = error instanceof Error ? error.message : String(error);
      return {
        query,
        cacheHit: false,
        hits: 0,
        nextStep: `source bootstrap failed: ${errorMessage}`,
      };
    }
  }),
);

const nowCT = formatCTTimestamp(new Date());
const digestLines = [
  `Session boot: ${nowCT}`,
  `Memory: ${firstNonEmptyLine(memoryIndex)}`,
  `Lessons: ${firstNonEmptyLine(keyLessons)}`,
  `Operator prefs: ${firstNonEmptyLine(operatorPrefs)}`,
  `Bootstrap queries: ${sourceBootstrapQueries.join("; ")}`,
];

const briefBody = [
  "# Session Brief (auto-generated)",
  `Generated: ${nowCT}`,
  "",
  "## Digest (5 lines)",
  ...digestLines.map((line) => `- ${line}`),
  "",
  "## Sources",
  `- ${memoryIndexPath}`,
  `- ${keyLessonsPath}`,
  `- ${operatorPrefsPath}`,
  "",
  "## Source Bootstrap",
  ...sourceBootstrapResults.map(
    (result) =>
      `- ${result.query}: ${result.hits} offline hit(s), cache ${result.cacheHit ? "hit" : "miss"}, next -> ${result.nextStep}`,
  ),
  "",
  "## Notes",
  "- This file is generated by scripts/session-boot.mjs.",
  "- Source bootstrap is automatically populated through scripts/query-source-ladder.mjs.",
  "- Update source files, not this brief.",
];

await fs.mkdir(path.dirname(outPath), { recursive: true });
await fs.writeFile(outPath, `${briefBody.join("\n")}\n`, "utf8");

console.log(digestLines.join("\n"));
